### ISSUE TITLE
Textual labels to appear on hover only (2 points)

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/Provisualizer#11]
Textual labels to appear only when user hovers over a node (agency or function). This will reduce the textual clutter which occurs when a particular search returns a large number of agencies or functions. This will also allow for labels to be larger, with multiple lines of text, and without truncation of the text.

**Comment by Conal-Tuohy** [comment]
Resolved in d1aa81fdefbed47102242525a2e63739f7e91729

**Comment by Conal-Tuohy** [comment]
@asaletourneau asks:

"Can you please ensure that every time the cursor rolls over a node the label stays on please. I think this is preferable to giving the user an option to toggle all labels on or off which I think would be much more work?"

Yes the toggle would be more work. Not that it would be a huge amount of work, it's just that the "once shown, never hidden" rule is trivial. I will do this, but I think it may have some other design repercussions to be honest.

**Comment by Conal-Tuohy** [comment]
This from Mark Seabrook is related too:

"It's much better not having the labels visible but (and there's always a but) then you have to hover over each one to find what you're looking for. Maybe a toggle for text on/off? (Off by default) Maybe another drop-down based on just what is on the screen (the results of the search)? I know you've got everything listed but tailored to the search might be good.
Should the main hub have visible text?"

What is "the main hub"? That would be node (or nodes!) that matched the current query? And excluding nodes which appear on because they are connected to nodes that match the current query?

**Comment by Conal-Tuohy** [comment]
Re-resolved in commit 636ea77

**Comment by asaletourneau** [comment]
Hi,

Just got back from a very long meeting and saw this. I think this is 
really good for the user to be able to see multiple labels as they explore 
the nodes.

 I think when it comes to finishing the last 3 front end tasks it would be 
really useful to have a button on the Revised Toolbar that allows the user 
to clear all labels, especially if they begin to clutter the space! What 
do you think about these tweaks?

Cheers

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov,au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
Hi Asa

I have closed the "label hiding" issue because the change to the
functionality which it specified is made, and even tweaked.

These other ideas are really additions, though. I think they should go in a
new issue. I also think that in terms of priority the the issue should wait
until after the other main issues are addressed. It can't be as much of a
priority as getting the help displayed, I would have thought?

This kind of thing is pretty easy to tweak, though, so feel free to canvas
some other ideas as well.

Thanks for the reminder about Font Awesome!

I am feeling a bit cruddy actually ... I have 5 days' worth of antiobiotics
which should see me in good form by the time we head off on holiday on
Saturday night. Can you talk tomorrow?

Cheers

C

On 16 February 2016 at 15:18, Asa Letourneau <notifications@github.com>
wrote:

> Hi,
>
> Just got back from a very long meeting and saw this. I think this is
> really good for the user to be able to see multiple labels as they explore
> the nodes.
>
> I think when it comes to finishing the last 3 front end tasks it would be
> really useful to have a button on the Revised Toolbar that allows the user
> to clear all labels, especially if they begin to clutter the space! What
> do you think about these tweaks?
>
> Cheers
>
> Asa Letourneau
> Online Engagement Officer
> T: 03 9348 5759 F: 03 9348 5656
> asa.letourneau@prov.vic.gov,au
>
> Public Record Office Victoria
> Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
> www.prov.vic.gov.au
> (Please Note that I work from home on Mondays with no remote access.)
>
> PROV News | http://prov.vic.gov.au/publications/blog
> Events | http://prov.vic.gov.au/whats-on
> Battle to Farm | http://soldiersettlement.prov.vic.gov.au/
>
> Our offices are located on the land of the Kulin Nations. We acknowledge
> and pay our respects to the Traditional Owners, past and present.
>
> You must not copy, disclose, distribute, store or otherwise use this
> material without permission . Any personal information in this email must
> be handled in accordance with the Information Privacy Act 2000 (Vic) and
> applicable laws. If you are not the intended recipient, please notify the
> sender immediately and destroy all copies of this email and any
> attachments . The State does not accept liability in connection with
> computer viruses , data corruption, delay, interruption, unauthorised
> access or use.
>
>
>
> From: Conal Tuohy <notifications@github.com>
> To: Conal-Tuohy/Provisualizer <Provisualizer@noreply.github.com>,
> Cc: Asa Letourneau/DPC@DPC
> Date: 16/02/2016 03:49 PM
> Subject: Re: [Provisualizer] Textual labels to appear on hover only
> (2 points) (#11)
>
>
>
> Re-resolved in commit 636ea77
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Conal-Tuohy/Provisualizer/issues/11#issuecomment-184525857>
> .
>



-- 
Conal Tuohy
http://conaltuohy.com/
@conal_tuohy
+61-466-324297

**Comment by asaletourneau** [comment]
Thanks so much for your help. You are defdinitely the voice of reason at 
the moment! I've had  more of a look and totally agree that the help text 
is definbitely the priority followed by the revised toolbar, a button to 
clear all labels whenever the user desires, and not forgetting the 
Deployment Manual, of which PROV will be unable to host the tool!

I'll call you tomorrow, not tonight. Sorry you're not feeling well and 
look forward to a nice relaxing beer with you one day when all this is 
over, hopefully in Sydney if we get invited to the ASA. Haven't heard 
anything yet but will keep you posted!
Cheers

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov,au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.
