### ISSUE TITLE
 legend and basic user guide to float within the visualisation itself (3 points)

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/Provisualizer#12]
legend and basic user guide, as supplied by PROV, to float within the visualisation itself.

**Comment by asaletourneau** [comment]
[Tips .03 AL 20151029.pdf](https://github.com/Conal-Tuohy/Provisualizer/files/50441/Tips.03.AL.20151029.pdf)

Attaching the user guide text here for easy access, though you will have acess to the word doc in an email sent to you 29/10/15 at 4.47pm.

**Comment by asaletourneau** [comment]
I may have made a reference at some point in an early email exchange about this floating on the left of the screen but that is wrong, as shown in the  Revise graph visualization (2 points) #14  picture, it definitely  needs to float on the **right** of the screen. Thanks!

**Comment by asaletourneau** [comment]
I just realized that there is no way the floating 'Help' text is going to be legible at the required size to fit on the screen and not crowd out the visualization so if indeed this is the case I suspect it will have to be a pop up from a 'Help' button on the revised toolbar? I so hope you have enough time to get this front end work done because as I flagged early on,  it was always going to be quite tricky. Cheers

**Comment by Conal-Tuohy** [comment]
On our phone call we agreed we'd have a "help" button on the toolbar, and pop up a dialog box with the help text using jqueryui: http://jqueryui.com/dialog/#default

**Comment by asaletourneau** [comment]
Yes, thank god for your jquery suggestion! You are getting me over the 
line and I so hope you feel better real soon and have a smashing holiday!

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov,au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by asaletourneau** [comment]
I know you've been under the weather and you're only a couple of days away from your holiday but I'm wondering if there's any chance of you starting on the work we discussed yesterday over the phone and in our email exchange e.g. 
1. when the cursor rolls over a label and stays on it for 5 seconds the label appears
2. After appearing for 10 seconds the label needs to fade to invisibility
3.In addition to this we'll also have a 'Hide Labels' button on the revised toolbar that will allow the user to get make all labels disappear on demand.

and the  http://jqueryui.com/dialog/ stuff?
Cheers

**Comment by Conal-Tuohy** [comment]
Added help dialog in revision 636ea77 - the button to show and hide it will be added in dealing with issue #13 (revising the toolbar). Closing this issue now - please reopen it if there are further revisions needed.

**Comment by Conal-Tuohy** [comment]
Needs cosmetic work

**Comment by Conal-Tuohy** [comment]
added button to show help in revision 81d5a943c8c3456e59f70d092440a1488bd937ba

**Comment by Conal-Tuohy** [comment]
dialog box formatting corrected - only the font remains to be changed, and that's covered by issue #14
