### ISSUE TITLE
Revise graph visualization (2 points)

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/Provisualizer#14]
Edge lines in the visualization to be lengthened, relative to the size of the node circles. Text in the visualization to use fonts supplied by PROV.

**Comment by asaletourneau** [comment]
![look and feel guide](https://cloud.githubusercontent.com/assets/1021209/11551766/67102378-99d0-11e5-8aa7-fc2fb1625092.jpg)

My greatest concern is that we follow almost religiously the look and feel as reflected in this attached image which I think you are already understand. The one thing I would like to especially emphasize is the inclusion of the
large heading 'PROVISUALIZER' and beneath it the sub heading ' This visualisation will give you a high-level view of the archives'.

**Comment by Conal-Tuohy** [comment]
@asaletourneau can you point me at the fonts I should be using, again?

**Comment by asaletourneau** [comment]
Okay, just sent you the attachments from gmail because of issues sending 
old emails at the moment from PROV!

Cheers

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov,au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
completed in revision 4f03d57b184c8d36d38b1ffcbe6b1093ae897cbf
