### ISSUE TITLE
zoom out doesn't work without a mouse

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#30]
This may provide a lead for a solution?
If you are on a trackpad-equipped Mac, the zooming gestures are actually the Mac scrolling gestures: Scrolling up with two fingers zooms in, scrolling down with two fingers zooms out - Assuming that the Scroll direction in the Preferences is set to unnatural. ( http://stackoverflow.com/questions/16861315/zoom-out-d3-force-directed-graph-without-using-mouse-wheel)  _or shift double click apparently._ Are you able to try and let me know? If it works can you add a sentence to this effect in the help text in the appropriate place?

**Comment by Conal-Tuohy** [comment]
On my Android devices I can confirm that the standard Android zoom gestures (pinching) work, and in that case I don't think it's worth even mentioning that in the help, because it's what Android users will simple expect. For desktop users, the mouse-wheel scrolling is not so normal (it usually scrolls a page up and down), so that is worth mentioning I think.

I don't have a Mac or really any experience with them, so I can't comment on that.

**Comment by asaletourneau** [comment]
i'm now testing on my colleagues Asus laptop and the shift double click zooms out! Might be worth mentioning that for PC laptop users without a mouse, shift double click will zoom out. Only saying this because there must be lots of people who don'y bother using a mouse with a laptop?
