### ISSUE TITLE
Help jquery dialogue box scroll bar bug

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#34]
I can confirm that the Help jquery dialogue box scroll bar no longer appears on an ipad, iphone or macbookpro. See attached screnshots from iphone and macbookpro
![no scroll bug iphone](https://cloud.githubusercontent.com/assets/1021209/15563721/d6d3bb5e-234e-11e6-9cff-c408461cf71a.jpg)
![no scroll bug macbookpro](https://cloud.githubusercontent.com/assets/1021209/15563723/d813428c-234e-11e6-80ae-c46aab27c44a.jpg)

I should have added that the scroll bar does appear and work in IE, Firefox and Chrome.

**Comment by asaletourneau** [comment]
Scroll-bar appeared successfully in my macbookpro at home yesterday but still not on Ipad or Iphone.

**Comment by asaletourneau** [comment]
Scroll bar and box drag **now working** on Mac-book Pro but still not on Iphone and Ipad like it used to.

**Comment by Conal-Tuohy** [comment]
Turns out this is a common complaint of web developers developing for the standard iOS Safari browser. There is a custom css property that makes Safari behave according to spec, which I've added. If you can check this please @asaletourneau I'd appreciate it, and if it is fixed, feel free to close this issue.

**Comment by asaletourneau** [comment]
Help box scroll bar not appearing and scroll not working on Iphone. Help box scroll bar not appearing on Ipad but scroll working!
Will leave this open for now.
